version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - redis  # Backend depends on Redis - Used for caching and session storage
    environment:
      NODE_ENV: production
      FRONTEND_URL: http://localhost:5173  # Frontend URL for CORS
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"  # Expose frontend on 5173
    depends_on:
      - backend  # Frontend depends on backend	
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000  # Frontend connects to backend via localhost
    networks:
      - app-network

  redis:  
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Create a bridge network for communication between containers
    # This allows the backend and frontend to communicate with each other